# Generated by Django 2.2.4 on 2019-08-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JoueursSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journee', models.IntegerField()),
                ('j1', models.IntegerField(blank=True, null=True)),
                ('j2', models.IntegerField(blank=True, null=True)),
                ('j3', models.IntegerField(blank=True, null=True)),
                ('j4', models.IntegerField(blank=True, null=True)),
                ('j5', models.IntegerField(blank=True, null=True)),
                ('j6', models.IntegerField(blank=True, null=True)),
                ('j7', models.IntegerField(blank=True, null=True)),
                ('j8', models.IntegerField(blank=True, null=True)),
                ('j9', models.IntegerField(blank=True, null=True)),
                ('j10', models.IntegerField(blank=True, null=True)),
                ('j11', models.IntegerField(blank=True, null=True)),
                ('j12', models.IntegerField(blank=True, null=True)),
                ('j13', models.IntegerField(blank=True, null=True)),
                ('j14', models.IntegerField(blank=True, null=True)),
                ('j15', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchsRonvau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipeA', models.CharField(max_length=50)),
                ('equipeB', models.CharField(max_length=50)),
                ('journee', models.IntegerField()),
            ],
        ),
    ]
